spring:
  profiles:
    active: default
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:payment_service}
    username: ${DB_USER:pgAdmin}
    password: ${DB_PASSWORD:password}
  application:
    name: ${SPRING_APP_NAME:payment-service}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${SERVER_PORT:8089}

configs:
  rabbitmq:
    queues:
      deleteBalance: "deletePendingBalanceQueue"

microserviceUrls:
  user-service: http://user-service:8081

security:
  paths:
    permittedRequestsForAllUsers:
      - method: GET
        pattern: /actuator/**
      - method: GET
        pattern: /swagger-ui/**
      - method: GET
        pattern: /v3/api-docs/**
      - method: POST
        pattern: /v1/user/balance
      - method: DELETE
        pattern: /v1/user/balance/{id}
      - method: POST
        pattern: /v1/payments/pay
      - method: PUT
        pattern: /v1/user/balance/withdraw/{id}
      - method: PUT
        pattern: /v1/user/balance/deposit/{id}
    permittedRequestsForUsersOrAdminOrSuperAdmin:
      - method: GET
        pattern: /v1/user/balance/{id}
      - method: POST
        pattern: /v1/transactions/deposit
      - method: POST
        pattern: /v1/transactions/withdraw
    permittedRequestsForAdminOrSuperAdmin:
      - method: GET
        pattern: /v1/payments
    permittedRequestForSuperAdmin: [ ]
