spring:
  profiles:
    active: default
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:payment_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  application:
    name: ${SPRING_APP_NAME:payment-service}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${SERVER_PORT:8089}

configs:
  rabbitmq:
    queues:
      deleteBalance: "deletePendingBalanceQueue"

microserviceUrls:
  auth-service: http://auth-service:8080
  user-service: http://user-service:8081